

class GeneradorInformes {

    public crearInforme(datos:string):string{

        //Analizar los datos recibidos y preprocesarlos
        //...
        //...
        //...
        //...
        //...
        //...
        //...

        //Ejecutar consultas a la bb.dd.
        //...
        //...
        //...
        //...
        //...
        //...
        //...

        //Cruzar los datos obtenidos
        //...
        //...
        //...
        //...
        //...
        //...

        //Formatear el informe
        //...
        //...
        //...
        //...
        //...
        //...
        //...
        //...
        return "INFORME"

    }

}


class GeneradorInformes_ {

    public crearInforme(datos:string):string{
        let datosPreprocesados = this.preprocesarDatos(datos)
        let resultadoConsultas = this.ejecutarConsultas(datosPreprocesados)
        let datosCruzados      = this.cruzarDatos(resultadoConsultas)
        let informe            = this.formatearInforme(datosCruzados)
        return informe
    }
    
    private preprocesarDatos(datos:string):string{
        //Analizar los datos recibidos y preprocesarlos
        //...
        //...
        //...
        //...
        //...
        return "datos preprocesados"
    }
    
    private ejecutarConsultas(datos:string):string{
        //Ejecutar consultas a la bb.dd.
        //...
        //...
        //...
        //...
        //...
        //...
        return "resultado de las consultas"
    }
    
    private cruzarDatos(datos:string):string{
        //Cruzar los datos obtenidos
        //...
        //...
        //...
        //...
        //...
        //...
        return "datos cruzados"
    }
    
    private formatearInforme(datos:string):string{
        //Formatear el informe
        //...
        //...
        //...
        //...
        //...
        //...
        return "INFORME"
    }
    
}

let generadorInformes:GeneradorInformes = new GeneradorInformes()
let informe:string = generadorInformes.crearInforme("DATOS")

//generadorInformes.formatearInforme("X")


